name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run API endpoint tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "OPENAI_API_KEY is set: ${{ secrets.OPENAI_API_KEY != '' }}"
          pytest -vv backend/test_api_endpoints.py > api_test_results.txt
      - name: Run prompt tests with coverage
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd backend
          pytest --cov=test_prompts --cov-report=term-missing --cov-fail-under=95 -vv test_prompts.py > prompt_test_results.txt
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            api_test_results.txt
            backend/prompt_test_results.txt

  deploy:
    needs: test_backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        working-directory: backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          echo "FLY_API_TOKEN is set: ${{ secrets.FLY_API_TOKEN != '' }}" 
          flyctl deploy --remote-only

  notify_slack:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: GitHub Actions
          mention: here
          if_mention: failure,cancelled
          job_name: ${{ job.job }}
          channel: deployments
          icon_emoji: ':rocket:'
          username: DeployBot
          text: |
            Deployment to Fly.io ${{ job.status == 'success' && 'completed successfully! :white_check_mark:' || 'failed! :x:' }}
            
            *Repository:* ${{ github.repository }}
            *Branch:* ${{ github.ref_name }}
            *Commit:* ${{ github.sha }}
            *Author:* ${{ github.actor }}
            *Commit Message:* ${{ github.event.head_commit.message }}
            
            *Workflow:* ${{ github.workflow }}
            *Run ID:* ${{ github.run_id }}
            
            *Test Results:*
            - [API Test Results](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/api_test_results.txt)
            - [Prompt Test Results](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/prompt_test_results.txt)
            
            [View Action Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
